default_language_version:
  python: python3.11

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
      - id: trailing-whitespace
        exclude: ^.*\.md$
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

    - repo: https://github.com/ambv/black
      rev: 24.10.0
      hooks:
        - id: black
          types: [python]

    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.7.0
      hooks:
        - id: ruff
          args: [--fix, --exit-non-zero-on-fix]
        - id: ruff-format

    - repo: https://github.com/crate-ci/typos
      rev: v1.25.0
      hooks:
        - id: typos

    - repo: https://github.com/PyCQA/flake8
      rev: 7.1.1
      hooks:
        - id: flake8
          exclude: ^test/
          args: [--max-line-length=120, "--ignore=E701"]
